spring.application.name=database-api
server.port=7760

#database properties /configuration for connecting MySQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Naukri.com-Database
spring.datasource.username=postgres
spring.datasource.password=Vicky098@
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#this will show the sql queries running internally in console
#spring.jpa.show-sql=true
#for automatically update database after every change
spring.jpa.hibernate.ddl-auto=update
#it converts the java data types into database data type
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect